FROM python:3
USER root

ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV TZ JST-9

RUN pip install -U pip
RUN pip install mysql
RUN pip install astor
RUN pip install requests-html
RUN pip install mysqlclient
RUN pip install google-api-python-client
RUN pip install beautifulsoup4



